---
sidebar: sidebar 
permalink: scpivs44_role_based_access_control.html 
keywords:  
summary: El plugin de SnapCenter para VMware vSphere ofrece un nivel adicional de control de acceso basado en roles para la gestión de recursos virtualizados. El plugin es compatible con el control de acceso basado en roles de vCenter Server y de Data ONTAP. 
---
= Control de acceso basado en roles (RBAC)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El plugin de SnapCenter para VMware vSphere ofrece un nivel adicional de control de acceso basado en roles para la gestión de recursos virtualizados. El plugin es compatible con el control de acceso basado en roles de vCenter Server y de Data ONTAP.

El control de acceso basado en roles de SnapCenter y ONTAP se aplica únicamente a los trabajos coherentes con las aplicaciones (aplicación a través de VMDK) del servidor de SnapCenter. Si se utiliza el plugin de SnapCenter para VMware vSphere para admitir trabajos consistentes con la aplicación SnapCenter, debe asignar el rol SnapCenterAdmin; no puede cambiar los permisos del rol SnapCenterAdmin.

El plugin de SnapCenter para VMware vSphere incluye roles de vCenter predefinidos. Para ejecutar operaciones de SnapCenter, es necesario usar la interfaz gráfica de usuario de vCenter para añadir estos roles a los usuarios de vCenter Active Directory.

Es posible crear y modificar roles, así como añadir acceso a recursos para los usuarios en cualquier momento. Sin embargo, cuando se configura el plugin de SnapCenter para VMware vSphere por primera vez, es necesario añadir al menos algunos usuarios o grupos de Active Directory a roles, y luego otorgar acceso a recursos a esos usuarios o grupos.
