---
sidebar: sidebar 
permalink: scpivs44_upgrade_to_a_new_patch.html 
keywords:  
summary: Si va a actualizar a una nueva revisión de la misma versión, debe borrar la caché del plugin de SnapCenter para VMware vSphere en vCenter Web Server y reiniciar el servidor antes de la actualización o el registro. 
---
= Actualice a un nuevo parche de la misma versión del plugin de SnapCenter para VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si va a actualizar a una nueva revisión de la misma versión, debe borrar la caché del plugin de SnapCenter para VMware vSphere en vCenter Web Server y reiniciar el servidor antes de la actualización o el registro.

Si no se borra la caché del plugin, en las siguientes situaciones no se muestran los trabajos recientes en la consola ni en el monitor de trabajos:

* El plugin de SnapCenter para VMware vSphere se puso en marcha con vCenter y, posteriormente, se actualizó con una revisión en la misma versión.
* El dispositivo virtual de VMware de SnapCenter se puso en marcha en vCenter 1. Más tarde, este plugin de SnapCenter para VMware vSphere se registró en un nuevo sistema vCenter2. Se crea una nueva instancia del plugin de SnapCenter para VMware vSphere con un parche y registrada en vCenter1. Sin embargo, como vCenter1 sigue teniendo el plugin almacenado en caché del primer plugin de SnapCenter para VMware vSphere sin la revisión, la caché se debe borrar.




== Pasos para borrar la caché

. Localice el `vsphere-client-serenity` a continuación, busque la `com.netapp.scv.client-<release-number>` y elimínelo.
+
El nombre de la carpeta cambia para cada versión.

+
Consulte la documentación de VMware para conocer la ubicación de `vsphere-client-serenity` la carpeta para el sistema operativo.

. Reinicie vCenter Server.
+
Luego, puede actualizar el plugin de SnapCenter para VMware vSphere.


