---
sidebar: sidebar 
permalink: scpivs44_overview_of_different_snapcenter_guis.html 
keywords:  
summary: El plugin de SnapCenter para VMware vSphere es un plugin independiente que es diferente de otros plugins de SnapCenter. Debe utilizar la interfaz gráfica de usuario del cliente de VMware vSphere en vCenter para todas las operaciones de backup y restauración de máquinas virtuales, VMDK y almacenes de datos. 
---
= Descripción general de las distintas GUI de SnapCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
En el entorno de SnapCenter, es necesario usar la interfaz gráfica de usuario adecuada para realizar operaciones de protección de datos y gestión.

El plugin de SnapCenter para VMware vSphere es un plugin independiente que es diferente de otros plugins de SnapCenter. Debe utilizar la interfaz gráfica de usuario del cliente de VMware vSphere en vCenter para todas las operaciones de backup y restauración de máquinas virtuales, VMDK y almacenes de datos. También se usa la consola de la interfaz gráfica de usuario del cliente web para supervisar la lista de máquinas virtuales protegidas y sin proteger. Para el resto de operaciones de plugins de SnapCenter (plugins basados en aplicaciones), como backup y restauración y supervisión de trabajos, se usa la interfaz gráfica de usuario de SnapCenter.

Para proteger máquinas virtuales y almacenes de datos, se usa la interfaz de cliente de VMware vSphere. La interfaz gráfica de usuario del cliente web se integra con la tecnología Snapshot de NetApp en el sistema de almacenamiento. De esta forma, es posible realizar backup de máquinas virtuales y almacenes de datos en segundos y restaurar máquinas virtuales sin desconectar el host ESXi.

También hay una interfaz gráfica de usuario de gestión para realizar operaciones administrativas en el plugin de SnapCenter para VMware vSphere.

La siguiente tabla muestra las operaciones que realiza la interfaz gráfica de usuario de SnapCenter.

|===
| Utilice esta GUI… | Para ejecutar estas operaciones... | Y acceder a estos backups... 


| Interfaz gráfica de usuario de SnapCenter vSphere Client | Backup de máquinas virtuales y almacenes de datos conectar y desvincular el montaje de almacén de datos y desmontar máquinas virtuales y la restauración de archivos invitados y carpetas de VMDK | Backups de máquinas virtuales y almacenes de datos mediante la interfaz gráfica de usuario del cliente de VMware vSphere. 


| Interfaz gráfica de usuario de SnapCenter | Backup y restauración de bases de datos y aplicaciones en máquinas virtuales, incluida la protección de bases de datos para Microsoft SQL Server, Microsoft Exchange y Oracle. Clon de la base de datos | Backups realizados desde la interfaz gráfica de usuario de SnapCenter. 


| Interfaz gráfica de usuario de gestión del plugin de SnapCenter para VMware vSphere | Modificar la configuración de red generar un paquete de soporte Modificar la configuración del servidor NTP Deshabilitar/habilitar el plugin | N.A. 


| Interfaz gráfica de usuario de vCenter | Añadir roles de SCV a usuarios de vCenter Active Directory Añadir acceso a recursos para usuarios o grupos | N.A. 
|===
Para las operaciones de backup y restauración consistentes con las máquinas virtuales, se debe usar la interfaz gráfica de usuario del cliente VMware vSphere. Si bien es posible realizar algunas operaciones con las herramientas de VMware, por ejemplo, montar o cambiar el nombre de un almacén de datos, estas operaciones no se registrarán en el repositorio de SnapCenter y no se reconocerán.

SnapCenter no admite copias Snapshot únicas de bases de datos y máquinas virtuales. Los backups de máquinas virtuales y bases de datos deben programarse y ejecutarse por separado, lo cual crea snapshots independientes incluso si las bases de datos y las máquinas virtuales están alojadas en el mismo volumen. Los backups basados en aplicaciones deben programarse desde la interfaz gráfica de usuario de SnapCenter. Los backups consistentes con las máquinas virtuales deben programarse desde la interfaz gráfica de usuario del cliente de VMware vSphere.
