---
sidebar: sidebar 
permalink: scpivs44_rest_api_workflows__modify_built-in_schedules.html 
keywords:  
summary: Para modificar las programaciones integradas para trabajos de cliente de VMware vSphere mediante las API DE REST del plugin de SnapCenter para VMware vSphere, debe seguir la secuencia prescrita de las llamadas de API de REST. 
---
= Flujo de trabajo de API DE REST para modificar las programaciones integradas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Para modificar las programaciones integradas para trabajos de cliente de VMware vSphere mediante las API DE REST del plugin de SnapCenter para VMware vSphere, debe seguir la secuencia prescrita de las llamadas de API de REST.

Las programaciones integradas son las programaciones que se proporcionan como parte del producto; por ejemplo, la programación de volcado de la base de datos MySQL. Las siguientes programaciones se pueden modificar:
`Schedule-DatabaseDump`
`Schedule-PurgeBackups`
`Schedule-AsupDataCollection`
`Schedule-ComputeStorageSaving`
`Schedule-PurgeJobs`

Para cada API REST, añada `\https://<server>:<port>` En la parte frontal de la API DE REST para formar un extremo completo.

|===
| Paso | API REST | Comentarios 


| 1 | `/4.1/schedules` | `Get all built-in` programas obtiene una lista de los horarios de trabajo que se proporcionaron originalmente en el producto. Observe el nombre de la programación que desea modificar y la expresión cron asociada. 


| 2 | `/4.1/schedules` | `Modify any built-in schedule` cambia la programación indicada. Pase el nombre de la programación desde el Paso 1 y cree una nueva expresión cron para la programación. 
|===