---
sidebar: sidebar 
permalink: scpivs44_unregister_plugin_from_vcenter.html 
keywords:  
summary: Si detiene el servicio del plugin de SnapCenter para VMware vSphere en una instancia de vCenter que se encuentra en modo vinculado, los grupos de recursos no están disponibles en todos los vCenter vinculados, incluso cuando el servicio del plugin de SnapCenter para VMware vSphere se esté ejecutando en otros vCenter vinculados. Es necesario cancelar manualmente el registro de las extensiones del plugin de SnapCenter para VMware vSphere. 
---
= Cancele el registro del plugin de SnapCenter para VMware vSphere de vCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si detiene el servicio del plugin de SnapCenter para VMware vSphere en una instancia de vCenter que se encuentra en modo vinculado, los grupos de recursos no están disponibles en todos los vCenter vinculados, incluso cuando el servicio del plugin de SnapCenter para VMware vSphere se esté ejecutando en otros vCenter vinculados.

Es necesario cancelar manualmente el registro de las extensiones del plugin de SnapCenter para VMware vSphere.

.Pasos
. En la instancia de vCenter vinculada que tiene el servicio del plugin de SnapCenter para VMware vSphere detenido, desplácese hasta el administrador de referencia de objetos gestionados (MOB).
. En la opción Propiedades, seleccione *contenido* en la columna valor y, a continuación, en la siguiente pantalla seleccione *ExtensionManager* en la columna valor para mostrar una lista de las extensiones registradas.
. Cancele el registro de las extensiones `com.netapp.scv.client` y.. `com.netapp.aegis`.

