---
sidebar: sidebar 
permalink: scpivs44_minimum_ontap_privileges_required.html 
keywords:  
summary: Los privilegios mínimos requeridos de ONTAP varían en función de los plugins de SnapCenter que utilice para la protección de datos. 
---
= Se requieren privilegios de ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Los privilegios mínimos requeridos de ONTAP varían en función de los plugins de SnapCenter que utilice para la protección de datos.


NOTE: A partir del plugin de SnapCenter para VMware (SCV) 5,0, es necesario añadir aplicaciones de tipo HTTP y ONTAPI como métodos de inicio de sesión de usuario para cualquier usuario de ONTAP con acceso personalizado basado en roles a SCV. Sin el acceso a estas aplicaciones, los backups fallarán. Es necesario reiniciar el servicio de SCV para reconocer los cambios en los métodos de inicio de sesión de usuarios de ONTAP.



== Privilegios mínimos requeridos de ONTAP

Todos los plugins de SnapCenter requieren los siguientes privilegios mínimos.

|===


| Comandos de acceso total: Privilegios mínimos requeridos para ONTAP 8.3 y versiones posteriores 


| se muestra la identidad del clúster 


| event generate-autosupport-log 


| se muestra el historial del trabajo
exposición de trabajos
detención de trabajo 


| lun lun lun create lun delete lun igroup add lun igroup create lun igroup delete lun igroup rename lun igroup show lun mapping add-reporting-nodes lun mapping create lun mapping delete lun mapping remove-reporting-nodes mapa de lun show lun modify lun move-in-volume lun offline lun online lun persistent-reservation clear lun redimensione lun serial lun muestra de lun 


| lista de destinos de snapmirror política de snapmirror complemento regla de snapmirror política de modificación-regla de snapmirror política de eliminación regla de snapmirror política de snapmirror mostrar snapmirror restaurar snapmirror mostrar el historial de snapmirror actualización de snapmirror conjunto de complementos de snapmirror 


| Versión 


| crear el clon de volumen
show de clon de volumen
inicio de división de clon de volumen
detención de división de clon de volumen
cree el volumen
eliminar el volumen
destrucción del volumen
crear el archivo de volumen
uso show-disk del archivo de volumen
volumen sin conexión
volumen en línea
modificación del volumen
crear el qtree de volúmenes
eliminación de qtree de volumen
modificación del qtree del volumen
se muestra volume qtree
restricción de volumen
visualización de volumen
crear snapshots de volumen
eliminación de snapshots de volumen
modificación de las copias de snapshot de volumen
cambio de nombre de copias de snapshot de volumen
restauración de copias snapshot de volumen
archivo de restauración de snapshots de volumen
visualización de copias de snapshot de volumen
desmonte el volumen 


| vserver cifs share crea vserver cifs share delete vserver cifs shadowcopy show vserver cifs share show vserver cifs share show vserver show vserver vserver show vserver vserver export-policy vserver export-policy vserver create vserver export-policy create vserver export-policy delete vserver export-policy create vserver export-policy policy create vserver export-policy show vserver iscsi connection show vserver show vserver show network interface interfaz de red: grupos de recuperación tras fallos de la interfaz de red se muestra 
|===
|===
| Comandos de solo lectura: Privilegios mínimos requeridos para ONTAP 8.3 y versiones posteriores 


| vserver peer 
|===

NOTE: Puede ignorar los mensajes de advertencia acerca de los comandos de vServer no compatibles.



== Información adicional sobre ONTAP

* Si utiliza ONTAP 8.2.x:
+
Debe iniciar sesión como `vsadmin` En la máquina virtual de almacenamiento con los privilegios adecuados para las operaciones del plugin de SnapCenter para VMware vSphere.

* Si utiliza ONTAP 8.3 y versiones posteriores:
+
Debe iniciar sesión como `vsadmin` o con un rol que tenga los privilegios mínimos indicados en las tablas anteriores.

* Debe ser el administrador del clúster para crear y gestionar los roles de usuario. Puede asociar los usuarios con la máquina virtual de almacenamiento del clúster o con la máquina virtual de almacenamiento.
* Necesita ONTAP 9.12.1 o versiones posteriores para usar la funcionalidad de continuidad del negocio de SnapMirror (SM-BC).
* Para utilizar la función Instantánea a prueba de manipulaciones (TPS):
+
** Necesita ONTAP 9.13.1 y versiones posteriores para SAN
** Necesita ONTAP 9.12.1 y versiones posteriores para NFS





NOTE: Para ONTAP versión 9.11.1 y posteriores, la comunicación con el clúster de ONTAP se realiza a través de las API DE REST. El usuario de ONTAP debe tener activada la aplicación http. Sin embargo, si se encuentran problemas con las API REST DE ONTAP, la clave de configuración 'FORCE_zapi' ayuda a la conmutación al flujo de trabajo de ZAPI tradicional. Puede que necesite agregar o actualizar esta clave mediante LAS API DE configuración y establecerla en true. Consulte el artículo de la base de conocimientos, https://kb.netapp.com/mgmt/SnapCenter/How_to_use_RestAPI_to_edit_configuration_parameters_in_SCV["Cómo usar RestAPI para editar parámetros de configuración en SCV"].
