---
sidebar: sidebar 
permalink: scpivs44_minimum_vcenter_privileges_required.html 
keywords:  
summary: Antes de iniciar la implementación del plugin de SnapCenter para VMware vSphere, debe asegurarse de contar con los privilegios mínimos de vCenter requeridos. 
---
= Privilegios mínimos requeridos de vCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Antes de iniciar la implementación del plugin de SnapCenter para VMware vSphere, debe asegurarse de contar con los privilegios mínimos de vCenter requeridos.



== Privilegios requeridos para la función de administrador de vCenter

Datastore.AllocateSpace Datastore.Browse Datastore.Delete Datastore.FileManagement Datastore.Move Datastore.Rename Extension.Register Extension.Unregister Extension.Update Host.Config.AdvancedConfig Host.Config.Resources Host.Config.Host.Config.Config.Storage Host.Local.CreateVM Host.Local.DeleteVM Host.Local.ReconfigVM Network.Assign Resource.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.VirtualMachine.Virtual



== Privilegios requeridos específicos del plugin de SnapCenter para VMware vCenter

|===


| *Privilegios* | *Etiqueta* 


| NetappSCV.Guest.RestoreFile | Restauración de archivos invitados 


| NetappSCV.Recovery.MountUnMount | Montar/desmontar 


| NetappSCV.Backup.DeleteBackupJob | Eliminar grupo de recursos/copia de seguridad 


| NetappSCV.Configure.ConfigureStorageSystems.Delete | Quitar sistemas de almacenamiento 


| NetappSCV.View | Ver 


| NetappSCV.Recovery.RecoverVM | Recuperar la máquina virtual 


| NetappSCV.Configure.ConfigureStorageSystems.AddUpdate | Añadir/modificar sistemas de almacenamiento 


| NetappSCV.Backup.BackupNow | Realice su backup ahora 


| NetappSCV.Guest.Configure | Configuración de invitado 


| NetappSCV.Configure.ConfigureSnapCenter Server | Configure el servidor SnapCenter 


| NetappSCV.Backup.BackupExeted | Crear grupo de recursos 
|===