---
sidebar: sidebar 
permalink: scpivs44_overview_of_different_snapcenter_guis.html 
keywords:  
summary: El SnapCenter Plug-in for VMware vSphere es un complemento independiente que es diferente de otros complementos de SnapCenter .  Debe utilizar la interfaz de usuario del cliente VMware vSphere en vCenter para todas las operaciones de copia de seguridad y restauración de máquinas virtuales, VMDK y almacenes de datos. 
---
= Descripción general de las diferentes interfaces de usuario de SnapCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
En su entorno de SnapCenter , debe utilizar la interfaz de usuario adecuada para realizar operaciones de administración y protección de datos.

El SnapCenter Plug-in for VMware vSphere es un complemento independiente que es diferente de otros complementos de SnapCenter .  Debe utilizar la interfaz de usuario del cliente VMware vSphere en vCenter para todas las operaciones de copia de seguridad y restauración de máquinas virtuales, VMDK y almacenes de datos.  También puede utilizar la interfaz de usuario del cliente web Dashboard para supervisar la lista de máquinas virtuales protegidas y no protegidas.  Para todas las demás operaciones de complementos de SnapCenter (complementos basados ​​en aplicaciones), como copias de seguridad, restauraciones y monitoreo de trabajos, utilice la interfaz de usuario de SnapCenter .

Para proteger las máquinas virtuales y los almacenes de datos, utilice la interfaz de cliente VMware vSphere.  La interfaz de usuario del cliente web se integra con la tecnología de instantáneas de NetApp en el sistema de almacenamiento.  Esto le permite realizar copias de seguridad de máquinas virtuales y almacenes de datos en segundos y restaurar máquinas virtuales sin desconectar un host ESXi.

También hay una interfaz de usuario de administración para realizar operaciones administrativas en el SnapCenter Plug-in for VMware vSphere.

La siguiente tabla muestra las operaciones que realiza la interfaz de usuario de SnapCenter .

|===
| Utilice esta interfaz de usuario… | Para ejecutar estas operaciones... | Y acceder a estos backups... 


| Interfaz de usuario del cliente vSphere de SnapCenter | Backup de máquinas virtuales y almacenes de datos conectar y desvincular el montaje de almacén de datos y desmontar máquinas virtuales y la restauración de archivos invitados y carpetas de VMDK | Copias de seguridad de máquinas virtuales y almacenes de datos mediante la interfaz de usuario del cliente VMware vSphere. 


| Interfaz de usuario de SnapCenter | Backup y restauración de bases de datos y aplicaciones en máquinas virtuales, incluida la protección de bases de datos para Microsoft SQL Server, Microsoft Exchange y Oracle. Clon de la base de datos | Copias de seguridad realizadas mediante la interfaz de usuario de SnapCenter . 


| SnapCenter Plug-in for VMware vSphere | Modificar la configuración de red generar un paquete de soporte Modificar la configuración del servidor NTP Deshabilitar/habilitar el plugin | N.A. 


| Interfaz de usuario de vCenter | Añadir roles de SCV a usuarios de vCenter Active Directory Añadir acceso a recursos para usuarios o grupos | N.A. 
|===
Para realizar operaciones de copia de seguridad y restauración consistentes con VM, debe utilizar la interfaz de usuario del cliente VMware vSphere.  Si bien es posible realizar algunas operaciones utilizando herramientas de VMware, por ejemplo, montar o cambiar el nombre de un almacén de datos, esas operaciones no se registrarán en el repositorio de SnapCenter y no se reconocerán.

SnapCenter no admite instantáneas individuales de bases de datos y máquinas virtuales juntas.  Las copias de seguridad de las máquinas virtuales y las bases de datos deben programarse y ejecutarse de forma independiente, lo que crea instantáneas separadas incluso si las bases de datos y las máquinas virtuales están alojadas en el mismo volumen.  Las copias de seguridad basadas en aplicaciones deben programarse mediante la interfaz de usuario de SnapCenter ; las copias de seguridad consistentes con máquinas virtuales deben programarse mediante la interfaz de usuario del cliente VMware vSphere.
