---
sidebar: sidebar 
permalink: scpivs44_unmount_a_backup.html 
keywords:  
summary: Una vez que ya no se necesita el acceso a los archivos del almacén de datos, es posible desmontar un backup. 
---
= Desmontar un backup
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Una vez que ya no se necesita el acceso a los archivos del almacén de datos, es posible desmontar un backup.

Si una copia de seguridad aparece como montada en la interfaz de usuario del cliente VMware vSphere, pero no aparece en la pantalla de desmontaje de copia de seguridad, entonces debe usar la API REST. `/backup/{backup-Id}/cleanup` para limpiar los almacenes de datos fuera de límites y luego intentar el procedimiento de desmontaje nuevamente.

Si intenta montar una copia de seguridad de un almacén de datos NFS en una máquina virtual de almacenamiento (SVM) con el volumen raíz en una relación de espejo de uso compartido de carga, es posible que encuentre el error `You might have reached the maximum number of NFS volumes configured in the vCenter. Check the vSphere Client for any error messages.` Para evitar este problema, cambie la configuración de volúmenes máximos navegando a *ESX* > *Administrar* > *Configuración* > *Configuración avanzada del sistema* y cambiando el valor NFS.MaxVolumes.  El valor máximo es 256.

.Pasos
. En la página de accesos directos del cliente de VMware vSphere, seleccione *Storage*.
. En el panel de navegación de la izquierda, haga clic con el botón derecho en un almacén de datos, seleccione *SnapCenter Plug-in for VMware vSphere* en la lista desplegable y, a continuación, seleccione *Desmontar* en la lista desplegable secundaria.
+

IMPORTANT: Asegúrese de haber seleccionado el almacén de datos correcto para desmontar. De lo contrario, podría afectar al trabajo de producción.

. En el cuadro de diálogo *Unmount Cloned Datastore*, seleccione un almacén de datos, seleccione la casilla de verificación *Unmount the cloned datastore* y, a continuación, seleccione *Unmount*.

