---
sidebar: sidebar 
permalink: scpivs48_rest_apis_audit_logs.html 
keywords:  
summary: API DE REST para generar registros de auditoría 
---
= API DE REST para generar registros de auditoría
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede recoger los detalles del registro de auditoría de las API de REST de swagger, así como de la interfaz de usuario del plugin de SCV.

A continuación se indican las API de REST de swagger:

. OBTENGA 4.1/auditoría/registros: Obtenga datos de auditoría para todos los registros
. OBTENGA 4.1/audit/logs/{filename}: Obtenga los datos de auditoría para un archivo de registro específico
. POST 4.1/audit/Verify: Activa la verificación del registro de auditoría.
. GET 4,1/audit/config: Obtenga la configuración del servidor de syslog y auditoría
. PUT 4,1/audit/config: Actualice la configuración del servidor de syslog y auditoría


Para generar registros de auditoría para trabajos de cliente de VMware vSphere mediante las API DE REST del plugin de SnapCenter para VMware vSphere, debe usar las llamadas API DE REST para VMware vSphere.

Para cada API REST, añada `https://<server>:<port>/api` En la parte frontal de la API DE REST para formar un extremo completo.

Use las siguientes API DE REST en la sección Jobs para obtener información detallada sobre los trabajos:

|===
| API REST | Comentarios 


| `4.1/audit/logs` | devuelve archivos del registro de auditoría con datos de integridad 


| `4.1/audit/logs/{filename}` | obtenga un archivo de registro de auditoría específico con datos de integridad 


| `4.1/audit/verify` | activa la verificación de auditoría 


| `4.1/audit/syslogcert` | actualiza el certificado del servidor de syslog 
|===