---
sidebar: sidebar 
permalink: scpivs44_configure_credentials_for_vm_guest_file_restores.html 
keywords:  
summary: Cuando se asocia un disco virtual para operaciones de restauración de archivos o carpetas invitados, la máquina virtual de destino debe tener credenciales configuradas antes de la restauración. 
---
= Configurar las credenciales para restauraciones de archivos invitados de máquinas virtuales
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cuando se asocia un disco virtual para operaciones de restauración de archivos o carpetas invitados, la máquina virtual de destino debe tener credenciales configuradas antes de la restauración.

.Acerca de esta tarea
En la siguiente tabla, se enumeran los requisitos de credenciales para las operaciones de restauración en sistemas invitados.

|===
|  | Control de acceso del usuario activado | Control de acceso del usuario desactivado 


| Usuario de dominio | Un usuario de dominio con “administrador”, ya que el nombre de usuario funciona bien. Por ejemplo, “NetApp\Administrator”. Sin embargo, un usuario de dominio con “xyz” como nombre de usuario que pertenece a un grupo de administradores local no funcionará. Por ejemplo, no puede utilizar “NetApp\xyz”. | Ya sea un usuario de dominio con “administrador” como nombre de usuario o un usuario de dominio con “xyz” como nombre de usuario que pertenece a un grupo de administradores local, funciona bien. Por ejemplo, “NetApp\Administrator” o “NetApp\xyz”. 


| Usuario de grupo de trabajo | Un usuario local con “administrador” ya que el nombre de usuario funciona bien. Sin embargo, un usuario local con “xyz” como nombre de usuario que pertenece a un grupo de administradores local no funcionará. | Ya sea un usuario local con “administrador” como nombre de usuario o un usuario local con “xyz” como nombre de usuario que pertenece a un grupo de administradores local, funciona bien. Sin embargo, un usuario local con “xyz” como nombre de usuario que no pertenece al grupo de administradores local no funcionará. 
|===
En los ejemplos anteriores, “NetApp” es el nombre de dominio ficticio y “xyz” es el nombre de usuario local ficticio

.Pasos
. En la ventana de accesos directos del cliente de vSphere, seleccione *SnapCenter Plug-in for VMware vSphere* en plug-ins.
. En la navegación de la izquierda seleccione *Guest File Restore*.
. En la sección *Ejecutar como credenciales*, siga uno de estos procedimientos:
+
|===
| Para hacer esto… | Haga esto… 


| Utilizar credenciales existentes | Seleccione cualquiera de las credenciales configuradas. 


| Añadir nuevas credenciales  a| 
.. Seleccione *Agregar*.
.. En el cuadro de diálogo *credenciales Run as*, introduzca las credenciales. En Nombre de usuario, debe introducir “Administrador”.
.. Haga clic en *Seleccionar VM* y, a continuación, seleccione una VM en el cuadro de diálogo *Proxy VM*. Haga clic en *Guardar* para volver al cuadro de diálogo *Ejecutar como credenciales*. Seleccione la máquina virtual que debe utilizarse para autenticar las credenciales.


|===
+
El plugin de SnapCenter para VMware vSphere utiliza las credenciales seleccionadas para iniciar sesión en la máquina virtual seleccionada.

. Haga clic en *Guardar*.

