---
sidebar: sidebar 
permalink: scpivs44_detach_a_virtual_disk.html 
keywords:  
summary: Una vez que haya asociado un disco virtual para restaurar archivos concretos, podrá desvincular el disco virtual de la máquina virtual principal. 
---
= Desvincular un disco virtual
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Una vez que haya asociado un disco virtual para restaurar archivos concretos, podrá desvincular el disco virtual de la máquina virtual principal.

.Pasos
. En la interfaz gráfica de usuario del cliente de VMware vSphere, haga clic en *Menú* en la barra de herramientas y, a continuación, seleccione *VMs and Templates* en la lista desplegable.
. En el panel de navegación de la izquierda, seleccione una máquina virtual.
. En el panel de navegación de la izquierda, haga clic con el botón derecho en la máquina virtual, luego seleccione *SnapCenter Plug-in for VMware vSphere* en la lista desplegable y, a continuación, seleccione *Desasociar disco virtual* en la lista desplegable secundaria.
. En la pantalla * Detach virtual disk*, seleccione uno o varios discos que desee desvincular, luego seleccione la casilla de verificación * Detach the selected disk(s)* y haga clic en *DETACH*.
+

IMPORTANT: Asegúrese de seleccionar el disco virtual correcto. La selección de un disco incorrecto puede afectar al trabajo de producción.

. Opcional: Supervise el progreso de la operación en la sección *tareas recientes*.
+
Actualice la pantalla para que muestre información actualizada.

. Compruebe si el disco virtual está desvinculado siguiendo estos pasos:
+
.. Haga clic en *Menú* en la barra de herramientas y, a continuación, seleccione *VMs and Templates* en la lista desplegable.
.. En el panel de navegación de la izquierda, haga clic con el botón derecho en una VM y, a continuación, seleccione *Editar configuración* en la lista desplegable.
.. En la ventana *Editar configuración*, expanda la lista de cada disco duro para ver la lista de archivos de disco.
+
La página *Editar configuración* enumera los discos del equipo virtual. Puede expandir los detalles de cada disco duro para ver la lista de discos virtuales asociados.




