---
sidebar: sidebar 
permalink: scpivs44_access_rest_apis_using_the_swagger_api_web_page.html 
keywords:  
summary: Las API DE REST se exponen a través de la página web de Swagger. Es posible acceder a la página web de Swagger para mostrar las API DE REST de SnapCenter Server o del plugin de SnapCenter para VMware vSphere, y también para emitir manualmente una llamada API. Use las API de REST del plugin de SnapCenter para VMware vSphere para realizar operaciones de protección en máquinas virtuales y almacenes de datos. 
---
= Acceda a las API DE REST a través de la página web de API de Swagger
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las API DE REST se exponen a través de la página web de Swagger. Es posible acceder a la página web de Swagger para mostrar las API DE REST de SnapCenter Server o del plugin de SnapCenter para VMware vSphere, y también para emitir manualmente una llamada API. Utilice las API DE REST del plugin de SnapCenter para VMware vSphere para realizar operaciones en máquinas virtuales y almacenes de datos.

El plugin tiene páginas web de Swagger diferentes de las páginas web de SnapCenter Server Swagger.

.Antes de empezar
Para las API DE REST del plugin de SnapCenter para VMware vSphere, debe conocer la dirección IP o el nombre de host del plugin de SnapCenter para VMware vSphere.


NOTE: El plugin solo admite API DE REST con el fin de integrarse con aplicaciones de terceros y no admite cmdlets de PowerShell o CLI.

.Pasos
. Desde un explorador, introduzca la URL para acceder a la página web del plugin de Swagger:
+
`\https://<SCV_IP>:8144/api/swagger-ui/index.html`

+

IMPORTANT: No utilice los siguientes caracteres en la dirección URL de la API DE REST: +, . , %, y &.

+
.Ejemplo
Acceda a las API DE REST del plugin de SnapCenter para VMware vSphere:

+
`\https://<SCV_IP>:8144/api/swagger-ui/index.html`

+
`\https://OVAhost:8144/api/swagger-ui/index.html`

+
Inicie sesión con el mecanismo de autenticación de vCenter para generar el token.

. Haga clic en un tipo de recurso de la API para mostrar las API en ese tipo de recurso.

