---
sidebar: sidebar 
permalink: scpivs44_manage_resource_groups.html 
keywords:  
summary: Es posible crear, modificar y eliminar grupos de recursos de backup, así como realizar operaciones de backup en grupos de recursos. 
---
= Gestione grupos de recursos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Es posible crear, modificar y eliminar grupos de recursos de backup, así como realizar operaciones de backup en grupos de recursos.


NOTE: Los grupos de recursos se denominan trabajos de backup en VSC.



== Suspender y reanudar las operaciones en grupos de recursos

Pausar operaciones programadas en un grupo de recursos.  Habilítelos nuevamente cuando sea necesario.

.Pasos
. En el panel de navegación izquierdo del plugin SCV, seleccione *Resource Groups*, seleccione un grupo de recursos y seleccione *Suspender* (o seleccione *Reanudar*).
. En el cuadro de confirmación, seleccione *OK* para confirmar.


.Después de terminar
En la página Resource Groups, el estado del trabajo correspondiente al recurso suspendido es `Under_Maintenance`. Puede desplazarse hacia la derecha de la tabla para ver la columna Job Status.

Después de reanudar las operaciones de backup, el estado del trabajo cambia a. `Production`.



== Modificar grupos de recursos

Puede quitar o añadir recursos a grupos de recursos en vCenter, desvincular o asociar políticas, y modificar programaciones u otras opciones de grupos de recursos.

.Acerca de esta tarea
Si desea modificar el nombre de un grupo de recursos, no utilice los siguientes caracteres especiales en nombres de máquinas virtuales, almacenes de datos, políticas, backups o grupos de recursos:

% & * $ # @ ! \ / : * ? " < > - | ; ', y espacio. Se permite el carácter de guion bajo (_).

.Pasos
. En el panel de navegación izquierdo del plugin SCV, seleccione *Resource Groups*, luego seleccione un grupo de recursos y seleccione *Edit*.
. En la lista de la izquierda del asistente *Editar grupo de recursos*, seleccione la categoría que desea modificar e introduzca los cambios.
+
Puede realizar cambios en varias categorías. En esta opción también se pueden editar recursos secundarios protegidos.

. Selecciona *Siguiente* hasta que veas la página Resumen y luego selecciona *Finalizar*.




== Eliminar grupos de recursos

Elimine un grupo de recursos en vCenter si no necesita proteger los recursos.  Elimine todos los grupos de recursos antes de eliminar el SnapCenter Plug-in for VMware vSphere.

.Acerca de esta tarea
Todas las operaciones de eliminación de grupos de recursos se realizan como eliminaciones forzadas.  Cuando se elimina un grupo de recursos, el sistema separa todas las políticas del grupo de recursos de vCenter, elimina el grupo de recursos del SnapCenter Plug-in for VMware vSphere y elimina todas las copias de seguridad e instantáneas del grupo de recursos.


NOTE: En una relación SnapVault , no puede eliminar la última instantánea, por lo tanto, no puede eliminar el grupo de recursos.  Antes de eliminar un grupo de recursos en una relación de SnapVault , utilice el Administrador del sistema o la CLI de ONTAP para eliminar la relación y luego elimine la última instantánea.

.Pasos
. En el panel de navegación izquierdo del plugin SCV, seleccione *Resource Groups*, luego seleccione un grupo de recursos y seleccione *Delete*.
. En el cuadro de diálogo de confirmación *Eliminar grupo de recursos*, seleccione *Aceptar* para confirmar.  Eliminar un grupo de recursos no elimina la protección secundaria.  Si es necesario, utilice el Administrador del sistema para eliminar la protección secundaria.  Los grupos de consistencia creados para el grupo de recursos no se eliminan automáticamente; debe eliminarlos manualmente de ONTAP mediante el Administrador del sistema u otra interfaz compatible.

