---
sidebar: sidebar 
permalink: scpivs44_concepts_overview.html 
keywords:  
summary: 'El complemento de SnapCenter para VMware vSphere es un dispositivo virtual independiente (formato de dispositivo virtual abierto) que ofrece servicios de protección de datos para máquinas virtuales y almacenes de datos, y es compatible con servicios de protección de datos para plugins basados en aplicaciones de SnapCenter. Este documento describe cómo poner en marcha y utilizar el plugin de SnapCenter para VMware vSphere, e incluye información de inicio rápido.' 
---
= Información general del producto
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:firstname: [.lead]
:author: [.lead]
:authorinitials: [
:authors: [.lead]
:revnumber: 
:revdate: and supports data protection services for SnapCenter application-based plug-ins. This document describes how to deploy and use SnapCenter Plug-in for VMware vSphere and includes quick start information.


El plugin de SnapCenter para VMware vSphere se pone en marcha como un dispositivo virtual basado en Linux.

El plugin de SnapCenter para VMware vSphere añade la siguiente funcionalidad al entorno:

* Compatibilidad con operaciones de protección de datos consistentes con los fallos y consistentes con las máquinas virtuales.
+
Es posible usar la interfaz gráfica de usuario del cliente de VMware vSphere en vCenter para todas las operaciones de backup y restauración de máquinas virtuales de VMware (máquinas virtuales tradicionales y máquinas virtuales de VVol), VMDK y almacenes de datos. Para las máquinas virtuales de VVol (máquinas virtuales en almacenes de datos de VVol), solo se admiten backups consistentes con los fallos. También puede restaurar máquinas virtuales y VMDK, así como archivos y carpetas que residen en un sistema operativo invitado.

+
Al realizar backup de máquinas virtuales, VMDK y almacenes de datos, el plugin no admite RDM. Las tareas de backup para máquinas virtuales ignoran RDM. Si necesita realizar el backup de RDM, tiene que utilizar un plugin basado en aplicaciones de SnapCenter.

+
El plugin de SnapCenter para VMware vSphere incluye una base de datos de MySQL que contiene los metadatos del plugin de SnapCenter para VMware vSphere. Para la protección de datos coherente con los fallos y la máquina virtual, no es necesario instalar SnapCenter Server.

* Soporte para operaciones de protección de datos consistentes con las aplicaciones (aplicación a través de VMDK/RDM).
+
Puede utilizar la interfaz gráfica de usuario de SnapCenter y los complementos de aplicaciones de SnapCenter adecuados para todas las operaciones de backup y restauración de bases de datos y sistemas de archivos en almacenamiento primario y secundario en equipos virtuales.

+
SnapCenter aprovecha de forma nativa el plugin de SnapCenter para VMware vSphere en todas las operaciones de protección de datos en VMDK, asignaciones de dispositivos sin formato (RDM) y almacenes de datos NFS. Una vez puesto en marcha el dispositivo virtual, el plugin se encarga de todas las interacciones con vCenter. El plugin de SnapCenter para VMware vSphere es compatible con todos los plugins basados en aplicaciones de SnapCenter.

+
SnapCenter no admite copias Snapshot únicas de bases de datos y máquinas virtuales. Los backups de máquinas virtuales y bases de datos deben programarse y ejecutarse por separado, lo cual crea copias de Snapshot independientes, incluso si las bases de datos y las máquinas virtuales están alojadas en el mismo volumen. Programar los backups de aplicaciones de la base de datos mediante la interfaz gráfica de usuario de SnapCenter; programar los backups de máquinas virtuales y almacenes de datos mediante la interfaz gráfica de usuario del cliente VMware vSphere.

* Se requieren herramientas de VMware para snapshots consistentes con equipos virtuales
+
Si las herramientas de VMware no están instaladas y en ejecución, el sistema de archivos no se detiene y se crea una snapshot coherente con el bloqueo.

* Se requiere VMware Storage vMotion para operaciones de restauración en entornos DE SAN (VMFS)
+
El flujo de trabajo de restauración para el sistema de archivos de VMware (VMFS) utiliza la función VMware Storage vMotion. Storage vMotion forma parte de la licencia estándar de vSphere, pero no está disponible con las licencias de vSphere Essentials o Essentials Plus.

+
La mayoría de las operaciones de restauración en entornos de NFS utilizan la funcionalidad ONTAP nativa (por ejemplo, Single File SnapRestore) y no requieren VMware Storage vMotion.

* Se requieren las herramientas de ONTAP para VMware vSphere para configurar máquinas virtuales VMware VVOL.
+
Las herramientas de ONTAP se utilizan para aprovisionar y configurar el almacenamiento para vVols en ONTAP y en el cliente web de VMware.

+
Para obtener más información, consulte la documentación de las herramientas de ONTAP para VMware vSphere. Además, consulte la https://imt.netapp.com/matrix/imt.jsp?components=121034;&solution=1517&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"^] información más reciente sobre las versiones compatibles en las herramientas de ONTAP.

* El plugin de SnapCenter para VMware vSphere se pone en marcha como dispositivo virtual en una máquina virtual de Linux
+
Aunque el dispositivo virtual debe instalarse como máquina virtual Linux, el plugin de SnapCenter para VMware vSphere admite vCenter basados en Windows y Linux. De forma nativa, SnapCenter utiliza este plugin sin intervención del usuario para comunicarse con vCenter a fin de admitir los plugins basados en aplicaciones de SnapCenter que realizan operaciones de protección de datos en aplicaciones virtualizadas en Windows y Linux.



Además de estas funciones principales, el complemento SnapCenter para VMware vSphere es compatible con iSCSI, Fibre Channel, FCoE, NFS 3,0/4,1, VMFS 5,0/6,0, NVMe over FC y NVMe over TCP.

Para obtener la información más actualizada sobre las versiones compatibles, consulte https://imt.netapp.com/matrix/imt.jsp?components=121034;&solution=1517&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"^] (IMT).

Para obtener información sobre los protocolos NFS y el host ESXi, consulte la documentación de vSphere Storage que suministra VMware.

Para obtener información sobre la protección de datos de SnapCenter, consulte la información de protección de datos del plugin de SnapCenter en http://docs.netapp.com/us-en/snapcenter/index.html["Documentación de SnapCenter"^].

Para obtener información sobre las rutas de migración y actualización admitidas, consulte link:scpivs44_release_notes.html["Notas de la versión del plugin de SnapCenter para VMware vSphere"^].
