---
sidebar: sidebar 
permalink: scpivs44_create_backup_policies_for_vms_and_datastores.html 
keywords:  
summary: Debe crear políticas de backup antes de usar el plugin de SnapCenter para VMware vSphere con el fin de realizar el backup de las máquinas virtuales y los almacenes de datos. 
---
= Crear políticas de backup para máquinas virtuales y almacenes de datos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Debe crear políticas de backup antes de usar el plugin de SnapCenter para VMware vSphere con el fin de realizar el backup de las máquinas virtuales y los almacenes de datos.

.Antes de empezar
* Debe haber leído antes los requisitos previos.
* Debe haber configurado las relaciones de almacenamiento secundario.
+
** Si va a replicar snapshots en un almacenamiento secundario reflejado o en almacén, deben configurarse las relaciones y el administrador de SnapCenter debe haberle asignado las máquinas virtuales de almacenamiento tanto para el volumen de origen como para el volumen de destino.
** A fin de transferir correctamente snapshots a un almacenamiento secundario para relaciones de reflejo de versión flexible en un almacén de datos NFS o VMFS, asegúrese de que el tipo de política SnapMirror sea Asynchronous Mirror y que esté marcada la opción «all_source_snapshots».
** Cuando el número de Snapshot en el almacenamiento secundario (reflejo-almacén) alcanza el límite máximo, se produce un error en la actividad para registrar el backup y aplicar la retención en la operación de backup: `This snapshot is currently used as a reference snapshot by one or more SnapMirror relationships. Deleting the snapshot can cause future SnapMirror operations to fail.`
+
Para corregir este problema, configure la política de retención de SnapMirror para el almacenamiento secundario y evite alcanzar el límite máximo de instantáneas.

+
Para obtener información sobre cómo los administradores asignan recursos a los usuarios, consulte https://docs.netapp.com/us-en/snapcenter/concept/concept_types_of_role_based_access_control_in_snapcenter.html["Información de SnapCenter sobre el uso del control de acceso basado en roles"^].



* Si desea realizar backups consistentes con la máquina virtual, debe tener instaladas y en ejecución las herramientas de VMware. Se necesitan herramientas de VMware para desactivar las máquinas virtuales. No se admiten backups consistentes con las máquinas virtuales para máquinas virtuales VVol.
* La sincronización activa de SnapMirror permite que los servicios empresariales continúen funcionando incluso si se produce un fallo completo del sitio, lo que permite a las aplicaciones conmutar por error de forma transparente mediante una copia secundaria.
+

NOTE: La sincronización activa de SnapMirror solo se admite para almacenes de datos VMFS.

+
Para proteger un almacén de datos VMFS en una implementación de sincronización activa de SnapMirror, como administrador de SnapCenter necesita:

+
** Configure clusters y mediador como se describe en el informe técnico: https://www.netapp.com/pdf.html?item=/media/21888-tr-4878.pdf["TR-4878: Sincronización activa con SnapMirror (anteriormente SMBC)"].
** Añada el volumen asociado con el almacén de datos VMFS al grupo de coherencia y cree una relación de protección de datos mediante la política de protección _AutomatedFailOver_ o _AutomatedFailOverDuplex_ entre dos sistemas de almacenamiento de ONTAP. La política _AutomatedFailOverDuplex_ se admite a partir de la versión ONTAP 9.15.1.





NOTE: En una configuración de dispersión, el grupo de consistencia no es compatible con el sitio terciario.

.Acerca de esta tarea
La mayoría de los campos en estas páginas del asistente son claros y explicativos. La siguiente información describe algunos de los campos que pueden requerir explicación.

.Pasos
. En el panel de navegación izquierdo del plugin SCV, seleccione *Policies*.
. En la página *Policies*, selecciona *Create* para iniciar el asistente.
. En la página *Nueva Política de Copia de Seguridad*, introduzca el nombre de la política y una descripción.
+
** Modo vinculado
+
En el modo vinculado, cada vCenter tiene un dispositivo virtual independiente. Por lo tanto, se pueden usar nombres duplicados en vCenter. Sin embargo, debe crear la política en la misma instancia de vCenter que el grupo de recursos.

** Caracteres no admitidos
+
No utilice los siguientes caracteres especiales en máquinas virtuales, almacenes de datos, clústeres, políticas, backup o nombres de grupos de recursos: % & * $ # @ ! \ / : * ? " < > - | ; ' , .

+
Se permite el carácter de guion bajo (_).



. Especifique la configuración de frecuencia.
+
La política especifica solamente la frecuencia de backup. La programación de protección específica para realizar el backup se define en el grupo de recursos. Por lo tanto, dos o más grupos de recursos pueden compartir la misma política y frecuencia de backup y, a su vez, tener diferentes programaciones de backup.

. Seleccione la casilla de verificación *período de bloqueo* para habilitar el bloqueo de instantáneas. Puede seleccionar los períodos de bloqueo de instantáneas principales y secundarias como días/meses/años.
+

NOTE: Independientemente del valor de retención establecido en la política de ONTAP SnapMirror, la copia de Snapshot secundaria no se elimina antes del período de bloqueo de Snapshot secundario especificado.

. Especifique la configuración de retención.
+

IMPORTANT: Debe establecer el número de retención en 2 backups o un valor más alto si tiene pensado habilitar la replicación de SnapVault. Si configura el número de retención en 1 backup para conservar, la operación de retención podría fallar. Esto se debe a que la primera snapshot es la snapshot de referencia para la relación de SnapVault hasta que se replica una nueva snapshot en el destino.

+

NOTE: El valor de retención máximo es de 1018 backups para recursos en ONTAP 9.4 o posterior, y 254 backups para recursos en ONTAP 9.3 o anterior. Se producirá un error en los backups si la retención se establece en un valor superior a la versión de ONTAP subyacente. Esto también se aplica a almacenes de datos de expansión. Si un almacén de datos con extensión incluye recursos en ONTAP 9.3 y versiones anteriores, y en ONTAP 9.4 y versiones posteriores, asegúrese de configurar el valor de retención por debajo de 254.

. En los campos *replicación*, especifique el tipo de replicación al almacenamiento secundario, como se muestra en la siguiente tabla:
+
|===
| Para este campo… | Haga esto… 


| Actualice SnapMirror después del backup  a| 
Seleccione esta opción para crear copias reflejadas de los conjuntos de backups en otro volumen que tenga una relación de SnapMirror con el volumen de backup primario. Si un volumen está configurado con una relación mirror-vault, debe seleccionar sólo la opción *Actualizar SnapVault después de la copia de seguridad* si desea copiar las copias de seguridad en los destinos mirror-vault.


NOTE: Esta opción es compatible para almacenes de datos en FlexGroup Volumes en el plugin de SnapCenter para VMware vSphere 4.5 y versiones posteriores.


NOTE: Para proteger el almacén de datos VMFS en la implementación de sincronización activa de SnapMirror, debe completar los requisitos previos mencionados en la sección _Antes de comenzar_ y habilitar *Actualizar SnapMirror después de la copia de seguridad*.



| Actualice SnapVault después del backup  a| 
Seleccione esta opción para realizar una replicación de backup de disco a disco en otro volumen que tenga una relación de SnapVault con el volumen de backup primario.


IMPORTANT: Si se configura un volumen con una relación de reflejo-almacén, debe seleccionar solo esta opción si desea copiar backups en los destinos de reflejo-almacén.


NOTE: Esta opción es compatible para almacenes de datos en FlexGroup Volumes en el plugin de SnapCenter para VMware vSphere 4.5 y versiones posteriores.



| Etiqueta de Snapshot  a| 
Especifique una etiqueta opcional y personalizada que se añadirá a las copias de Snapshot de SnapVault y SnapMirror creadas con esta política. La etiqueta de Snapshot ayuda a distinguir las Snapshot creadas con esta política desde otras Snapshot del sistema de almacenamiento secundario.


NOTE: Se permite un máximo de 31 caracteres para las etiquetas de Snapshot.

|===
. Opcional: En los campos *Avanzado*, seleccione los campos necesarios. Los detalles del campo Advanced se enumeran en la siguiente tabla.
+
|===
| Para este campo… | Haga esto… 


| Consistencia de las máquinas virtuales  a| 
Marque esta casilla para poner en modo inactivo las máquinas virtuales y crear una Snapshot de VMware cada vez que se ejecute el trabajo de backup.

Esta opción no es compatible con vVols. Para máquinas virtuales VVol, solo se realizan backups consistentes con los fallos.


IMPORTANT: Para realizar backups consistentes de las máquinas virtuales, debe tener herramientas de VMware en ejecución en la máquina virtual. Si las herramientas de VMware no funcionan, se realiza un backup coherente con los fallos.


NOTE: Al marcar la casilla de consistencia de máquina virtual, las operaciones de backup pueden tardar más y requerir más espacio de almacenamiento. En este caso, las máquinas virtuales primero se ponen en modo inactivo, después VMware ejecuta una Snapshot de consistencia de máquina virtual, SnapCenter procede con su operación de backup y, a continuación, se reanudan las operaciones de máquina virtual. La memoria de invitado de la máquina virtual no está incluida en las instantáneas de consistencia de la máquina virtual.



| Incluir almacenes de datos con discos independientes | Marque esta casilla para incluir en el backup los almacenes de datos con discos independientes que contengan datos temporales. 


| Scripts  a| 
Especifique la ruta completa de scripts previos o scripts posteriores que desee que el plugin de SnapCenter para VMware vSphere ejecute antes o después de las operaciones de backup. Por ejemplo, se puede ejecutar un script para actualizar capturas SNMP, automatizar alertas y enviar registros. La ruta de acceso del script se valida en el momento en que se ejecuta el script.


NOTE: Los scripts previos y posteriores deben encontrarse en la máquina virtual del dispositivo virtual. Para introducir varios scripts, presione *Enter* después de cada ruta de script para enumerar cada script en una línea diferente. No se permite el carácter ";".

|===
. Selecciona *Añadir.*
+
Puede verificar si la política se creó y revisar su configuración seleccionando la política en la página Policies.


