---
sidebar: sidebar 
permalink: scpivs44_remove_plugin.html 
keywords:  
summary: Si ya no necesita utilizar las funciones de protección de datos de SnapCenter, debe deshabilitar el plugin de SnapCenter para VMware vSphere para cancelar el registro en vCenter, luego quitar el plugin de SnapCenter para VMware vSphere de vCenter y, a continuación, eliminar manualmente los archivos restantes. 
---
= Quite el plugin de SnapCenter para VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si ya no necesita utilizar las funciones de protección de datos de SnapCenter, debe deshabilitar el plugin de SnapCenter para VMware vSphere para cancelar el registro en vCenter, luego quitar el plugin de SnapCenter para VMware vSphere de vCenter y, a continuación, eliminar manualmente los archivos restantes.

.Antes de empezar
* Debe tener privilegios de administrador.
* Asegúrese de que no hay trabajos SnapCenter en ejecución.


.Pasos
. Inicie sesión en la interfaz gráfica de usuario de gestión del plugin de SnapCenter para VMware vSphere con el formato `\https://<OVA-IP-address>:8080`.
+
Cuando se implementa el plugin, se muestra la dirección IP del plugin de SnapCenter para VMware vSphere.

. Haga clic en *Configuración* en el panel de navegación izquierdo y, a continuación, anule la selección de la opción Servicio en la sección *Detalles del complemento* para desactivar el plugin.
. Inicie sesión en VMware vSphere.
. En la pantalla del navegador de la izquierda, haga clic con el botón derecho en la instancia del complemento SnapCenter para VMware vSphere (el nombre del `.tar` archivo que se utilizó cuando se implementó el dispositivo virtual) y seleccione *Eliminar del disco*.
. Si utilizó el plugin de SnapCenter para VMware vSphere para admitir otros plugins de SnapCenter para backups consistentes con las aplicaciones, inicie sesión en SnapCenter y quite el host de vSphere.


.Después de terminar
El dispositivo virtual sigue puesto en marcha, pero se quitó el plugin de SnapCenter para VMware vSphere.

Después de quitar la máquina virtual host para el plugin de SnapCenter para VMware vSphere, es posible que el plugin permanezca listado en vCenter hasta que se actualice la caché local de vCenter. Sin embargo, como se eliminó el plugin, no es posible realizar ninguna operación de SnapCenter VMware vSphere en ese host. Si desea actualizar la caché local de vCenter, primero asegúrese de que el dispositivo esté en estado deshabilitado en la página Configuración del plugin de SnapCenter para VMware vSphere y, a continuación, reinicie el servicio de cliente web de vCenter.
