---
sidebar: sidebar 
permalink: scpivs44_add_a_single_vm_or_datastore_to_a_resource_group.html 
keywords:  
summary: Puede añadir rápidamente una sola máquina virtual o un almacén de datos a cualquier grupo de recursos existente gestionado por el plugin de SnapCenter para VMware vSphere. 
---
= Añadir una sola máquina virtual o un almacén de datos a un grupo de recursos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede añadir rápidamente una sola máquina virtual o un almacén de datos a cualquier grupo de recursos existente gestionado por el plugin de SnapCenter para VMware vSphere.

.Acerca de esta tarea
Puede añadir almacenes de datos SAN y NAS, pero no VSAN o VVOL.

.Pasos
. En la GUI del cliente vSphere, seleccione *Menú* en la barra de herramientas y desplácese a la máquina virtual o al almacén de datos que desee agregar.
. En el panel de navegación de la izquierda, haga clic con el botón derecho en la máquina virtual o el almacén de datos, seleccione *SnapCenter Plug-in for VMware vSphere* > *Add to Resource Group* en la lista desplegable secundaria.
+
En primer lugar, el sistema comprueba que SnapCenter gestiona y es compatible con el sistema de almacenamiento en el que se encuentra la VM seleccionada y, a continuación, muestra la página *Agregar al grupo de recursos*. Si el mensaje `SnapCenter Compatibility Error` Se muestra, la máquina virtual seleccionada no es compatible con SnapCenter y, primero, debe añadir la máquina virtual de almacenamiento adecuada a SnapCenter.

. En la página *Agregar a grupo de recursos*, seleccione un grupo de recursos y, a continuación, seleccione *Aceptar*.
+
Cuando selecciona *OK*, el sistema primero comprueba que SnapCenter administra y es compatible con el almacenamiento en el que se encuentran las máquinas virtuales o los almacenes de datos seleccionados.

+
Si aparece el mensaje `Selected <resource-name> is not SnapCenter compatible` , significa que la máquina virtual o el almacén de datos que seleccionó no es compatible con SnapCenter. Consulte link:scpivs44_create_resource_groups_for_vms_and_datastores.html#manage-compatibility-check-failures["Gestione los fallos de comprobación de compatibilidad"] si desea obtener más información.


