---
sidebar: sidebar 
permalink: scpivs44_download_the_ova_open_virtual_appliance.html 
keywords:  
summary: El archivo .tar incluye OVA, que es un conjunto de microservicios para la protección de datos de máquinas virtuales y almacenes de datos y el archivo de certificado. 
---
= Descargue el dispositivo Open Virtual Appliance (OVA)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Antes de instalar el dispositivo Open Virtual Appliance (OVA), añada el certificado al para vCenter. El archivo .tar contiene los certificados OVA y Entrust raíz e intermedio, los certificados se pueden encontrar dentro de la carpeta de certificados. La puesta en marcha de OVA es compatible con VMware vCenter 7u1 y versiones posteriores.

En las versiones de VMware vCenter 7.0.3 y posteriores, el OVA firmado por el certificado Entrust ya no es de confianza. Debe realizar el siguiente procedimiento para resolver el problema.

.Pasos
. Para descargar el plugin de SnapCenter para VMware:
+
** Inicie sesión en el sitio de soporte de NetApp ( https://mysupport.netapp.com/products/index.html["https://mysupport.netapp.com/products/index.html"^]).
** En la lista de productos, seleccione *complemento SnapCenter para VMware vSphere* y, a continuación, haga clic en el botón *Descargar la versión más reciente*.
** Descargue el plugin de SnapCenter para VMware vSphere `.tar` archivar en cualquier ubicación.


. Extraiga el contenido del archivo tar. El archivo tar contiene el OVA y la carpeta certs. La carpeta certs contiene los certificados raíz e intermedio de Entrust.
. Inicie sesión con vSphere Client en vCenter Server.
. Vaya a *Administración > certificados > Gestión de certificados*.
. Junto a *certificados raíz de confianza*, haga clic en *Agregar*
+
** Vaya a la carpeta _certs_.
** Seleccione los certificados raíz y intermedio de Entrust.
** Instale cada certificado de uno en uno.


. Los certificados se agregan a un panel bajo *certificados raíz de confianza*. Una vez instalados los certificados, OVA puede verificarse e implementarse.



NOTE: Si el OVA descargado no se altera, la columna *Publisher* muestra *Certificado de confianza*.
