---
sidebar: sidebar 
permalink: scpivs44_properties_you_can_override.html 
keywords:  
summary: 'Puede utilizar las propiedades que aparecen en la `scbr.override` archivo de configuración para cambiar los valores predeterminados.' 
---
= Propiedades que se pueden anular
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede utilizar las propiedades que aparecen en la `scbr.override` archivo de configuración para cambiar los valores predeterminados.

* De forma predeterminada, la plantilla utiliza el símbolo hash para comentar las propiedades de configuración. Para utilizar una propiedad para modificar un valor de configuración, debe quitar `#` caracteres.
* Deberá reiniciar el servicio en el host del plugin de SnapCenter para VMware vSphere a fin de que los cambios se apliquen.


Puede utilizar las siguientes propiedades que se enumeran en la `scbr.override` archivo de configuración para cambiar los valores predeterminados.

* *dashboard.protected.vm.count.interval=7*
+
Especifica la cantidad de días durante los cuales la consola mostrará el estado de protección de la máquina virtual.

+
El valor predeterminado es "7".

* *Disable.debilidores=true*
+
Deshabilita los siguientes débilmente para el canal de comunicación entre el complemento de SnapCenter para VMware vSphere y SnapCenter, y los débilmente adicionales que aparezcan en la `include.weakCiphers`: TLS_RSA_WITH_AES_256_CBC_SHA256 TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 TLS_RSA_WITH_AES_128_CBC_SHA256 TLS_DHE_RSA_WITH_AES_128 128_256 256_SHA256_TLS_SJAS256_TLS_128_SHAS256_SHAS256_SATS_SHA256_SHA256_SHACLS_SHA256_SHA256_SHA256_SHA256_SHACLS_S256_SHACLS__S256_S256_SHACLS_S256_S256_SHACLS_SHACLS_SHA256_S

* *global.ds.exclude.pattern*
+
Especifica uno o varios almacenes de datos de VVol tradicionales que se van a excluir de operaciones de backup. Es posible especificar los almacenes de datos con cualquier expresión regular de Java válida.

+
Ejemplo 1: La expresión `global.ds.exclusion.pattern=.*21` excluye los almacenes de datos con un patrón común, por ejemplo `datastore21` y.. `dstest21` se excluiría.

+
Ejemplo 2: La expresión `global.ds.exclusion.pattern=ds-.*|^vol123` se excluyen todos los almacenes de datos que contienen `ds-` (por ejemplo `scvds-test`) o comience con `vol123`.

* *guestFileRestore.guest.operation.interval=5*
+
Especifica el intervalo de tiempo, en segundos, durante el cual el plugin de SnapCenter para VMware vSphere supervisa la finalización de las operaciones de invitado en el elemento invitado (disco en línea y Restaurar archivos). El tiempo de espera total lo establece `guestFileRestore.online.disk.timeout` y.. `guestFileRestore.restore.files.timeout`.

+
El valor predeterminado es "5".

* *GuestFileRestore.monitorInterval=30*
+
Especifica el intervalo de tiempo, en minutos, durante el cual el plugin de SnapCenter para VMware vSphere supervisa las sesiones de restauración de archivos invitados que expiraron. Toda sesión que se ejecute más allá del tiempo configurado se desconectará.

+
El valor predeterminado es "30".

* *GuestFileRestore.online.disk.timeout=100*
+
Especifica el tiempo, en segundos, durante el cual el plugin de SnapCenter para VMware vSphere espera a que se complete una operación de disco en línea en una máquina virtual invitada. Tenga en cuenta que hay un tiempo de espera adicional de 30 segundos antes de que el plugin sondee para completar la operación de disco en línea.

+
El valor predeterminado es "100".

* *GuestFileRestore.restore.files.timeout=3600*
+
Especifica el tiempo, en segundos, durante el cual el plugin de SnapCenter para VMware vSphere espera a que se complete una operación de restauración de archivos en una máquina virtual invitada. Si se supera el tiempo, el proceso finaliza y el trabajo se Marca como erróneo.

+
El valor predeterminado es "3600" (1 hora).

* *GuestFileRestore.robocopy.directory.flags=/R:0 /W:0 /ZB /COPYALL /EFSRAW /A-:SH /e /NJH /NDL /NP*
+
Especifica las marcas adicionales de robocopy que se van a utilizar al copiar directorios durante las operaciones de restauración de archivos invitados.

+
No lo retire `/NJH` o agregar `/NJS` debido a que se interrumpirá el análisis del resultado de la restauración.

+
No permita reintentos ilimitados (eliminando la `/R` bandera) porque esto podría causar una cantidad infinita de reintentos para copias fallidas.

+
Los valores predeterminados son `"/R:0 /W:0 /ZB /CopyAll /EFSRAW /A-:SH /e /NJH /NDL /NP"` .

* *GuestFileRestore.robocopy.file.flags=/R:0 /W:0 /ZB /COPYALL /EFSRAW /A-:SH /NJH /NDL /NP*
+
Especifica las marcas adicionales de robocopy que se van a utilizar al copiar archivos concretos durante las operaciones de restauración de archivos invitados.

+
No lo retire `/NJH` o agregar `/NJS` debido a que se interrumpirá el análisis del resultado de la restauración.

+
No permita reintentos ilimitados (eliminando la `/R` bandera) porque esto podría causar una cantidad infinita de reintentos para copias fallidas.

+
Los valores predeterminados son `"/R:0 /W:0 /ZB /CopyAll /EFSRAW /A-:SH /NJH /NDL /NP"`.

* *guestFileRestore.sessionTime=1440*
+
Especifica el tiempo, en minutos, durante el cual el plugin de SnapCenter para VMware vSphere mantiene activa una sesión de restauración de archivos invitados.

+
El valor predeterminado es "1440." (24 horas).

* *guestFileRestore.use.custom.online.disk.script=true*
+
Especifica si se va a utilizar un script personalizado para conectar discos y recuperar letras de unidades al crear sesiones de restauración de archivos invitados. El script debe estar ubicado en `[Install Path]  \etc\guestFileRestore_onlineDisk.ps1`. Con la instalación se proporciona un script predeterminado. Los valores `[Disk_Serial_Number]`, `[Online_Disk_Output]`, y. `[Drive_Output]` se sustituyen en el script durante el proceso de asociación.

+
El valor predeterminado es "false".

* *include.esx.initiator.id.from.cluster=true*
+
Especifica que el plugin de SnapCenter para VMware vSphere debe incluir los ID de iniciadores iSCSI y FCP de todos los hosts ESXi que se encuentran en el clúster de la aplicación sobre flujos de trabajo de VMDK.

+
El valor predeterminado es "false".

* *Include.debilidores*
+
Cuando `disable.weakCiphers` se establece en `true`, especifica los códigos débiles que desea deshabilitar además de los cifrados débiles que `disable.weakCiphers` desactiva de forma predeterminada.

* *max.concurrente.ds.storage.query.count=15*
+
Especifica la cantidad máxima de llamadas simultáneas que el plugin de SnapCenter para VMware vSphere puede realizar a SnapCenter Server para detectar el espacio de almacenamiento de los almacenes de datos. El plugin realiza estas llamadas cuando reinicia el servicio Linux en el host de máquina virtual del plugin de SnapCenter para VMware vSphere.

* *nfs.datastore.mount.retry.count=3*
+
Especifica la cantidad máxima de veces que el plugin de SnapCenter para VMware vSphere intenta montar un volumen como almacén de datos NFS en vCenter.

+
El valor predeterminado es "3".

* *nfs.datastore.mount.retry.delay=60000*
+
Especifica el tiempo, en milisegundos, durante el cual el plugin de SnapCenter para VMware vSphere espera entre cada intento para montar un volumen como almacén de datos NFS en vCenter.

+
El valor predeterminado es "60000." (60 segundos).

* *script.virtual.machine.count.variable.name= VIRTUAL_MACHINES*
+
Especifica el nombre de variable del entorno que contiene el número de máquinas virtuales. Debe definir la variable antes de ejecutar los scripts definidos por el usuario durante un trabajo de backup.

+
Por ejemplo, VIRTUAL_MACHINES=2 significa que se está realizando el backup de dos máquinas virtuales.

* *script.virtual.machine.info.variable.name=VIRTUAL_MACHINE.%s*
+
Proporciona el nombre de la variable de entorno que contiene información acerca de la máquina virtual nth del backup. Debe configurar esta variable antes de ejecutar cualquier script definido por el usuario durante un backup.

+
Por ejemplo, la variable de entorno VIRTUAL_MACHINE.2 proporciona información acerca de la segunda máquina virtual del backup.

* *script.virtual.machine.info.format= %s|%s|%s|%s|%s|%s*
+
Proporciona información acerca de la máquina virtual. El formato de esta información, que se define en la variable de entorno, es el siguiente: `VM name|VM UUID| VM power state (on|off)|VM snapshot taken (true|false)|IP address(es)`

+
A continuación proponemos un ejemplo de la información que puede proporcionar:

+
`VIRTUAL_MACHINE.2=VM 1|564d6769-f07d-6e3b-68b1f3c29ba03a9a|POWERED_ON||true|10.0.4.2`

* *storage.connection.timeout=600000*
+
Especifica la cantidad de tiempo, en milisegundos, durante el cual el servidor de SnapCenter espera una respuesta del sistema de almacenamiento.

+
El valor predeterminado es "600000." (10 minutos).

* *vmware.esx.ip.kernel.ip.map*
+
No hay un valor predeterminado. Utilice este valor para asignar la dirección IP del host ESXi a la dirección IP de VMkernel. De forma predeterminada, el plugin de SnapCenter para VMware vSphere utiliza la dirección IP del adaptador de VMkernel de gestión del host ESXi. Si desea que el plugin de SnapCenter para VMware vSphere utilice una dirección IP del adaptador de VMkernel diferente, tendrá que proporcionar un valor de anulación.

+
En el ejemplo siguiente, la dirección IP del adaptador de VMkernel de gestión es 10.225.10.56. Sin embargo, el plugin de SnapCenter para VMware vSphere utiliza la dirección especificada de 10.225.11.57 y 10.225.11.58. Y si la dirección IP del adaptador de VMkernel de gestión es 10.225.10.60, el plugin utiliza la dirección 10.225.11.61.

+
`vmware.esx.ip.kernel.ip.map=10.225.10.56:10.225.11.57,10.225.11.58; 10.225.10.60:10.225.11.61`

* *vmware.max.concurrente.snapshots=30*
+
Especifica la cantidad máxima de snapshots de VMware que el plugin de SnapCenter para VMware vSphere realiza a la vez en el servidor.

+
Este número se comprueba por cada almacén de datos y se comprueba solo si se ha seleccionado la política "VM coherente". Si va a realizar backups consistentes con los fallos, esta configuración no se aplica.

+
El valor predeterminado es "30".

* *vmware.max.concurrent.snapshots.delete=30*
+
Especifica la cantidad máxima de operaciones de eliminación de snapshots de VMware, por cada almacén de datos, que el plugin de SnapCenter para VMware vSphere realiza a la vez en el servidor.

+
Este número se comprueba por cada almacén de datos.

+
El valor predeterminado es "30".

* *vmware.query.unresolved.retry.count=10*
+
Especifica la cantidad máxima de veces que el plugin de SnapCenter para VMware vSphere reintenta enviar una consulta sobre volúmenes sin resolver debido a «...time limit for holding off I/O...» errores.

+
El valor predeterminado es "10".

* *vmware.quiesce.retry.count=0*
+
Especifica la cantidad máxima de veces que el plugin de SnapCenter para VMware vSphere reintenta enviar consultas acerca de snapshots de VMware debido a «...time limit for holding off I/O...» errores durante una copia de seguridad.

+
El valor predeterminado es "0".

* *vmware.quiesce.retry.interval=5*
+
Especifica la cantidad de tiempo, en segundos, durante el cual el plugin de SnapCenter para VMware vSphere espera entre el envío de cada consulta sobre «...time limit for holding off I/O...» para snapshots de VMware. errores durante una copia de seguridad.

+
El valor predeterminado es "5".

* *vmware.query.unresolved.retry.delay= 60000*
+
Especifica la cantidad de tiempo, en milisegundos, durante el cual el plugin de SnapCenter para VMware vSphere espera entre cada envío de consultas sobre volúmenes sin resolver debido a «...time limit for holding off I/O...» errores. Este error se produce al clonar un almacén de datos VMFS.

+
El valor predeterminado es "60000." (60 segundos).

* *vmware.reconfig.vm.retry.count=10*
+
Especifica la cantidad máxima de veces que el plugin de SnapCenter para VMware vSphere reintenta enviar una consulta acerca de cómo reconfigurar una máquina virtual debido a «...time limit for holding off I/O...» errores.

+
El valor predeterminado es "10".

* *vmware.reconfig.vm.retry.delay=30000*
+
Especifica el tiempo máximo, en milisegundos, durante el cual el plugin de SnapCenter para VMware vSphere espera entre cada envío de consultas sobre la reconfiguración de una máquina virtual debido al «...time limit for holding off I/O.». errores.

+
El valor predeterminado es "30000." (30 segundos).

* *vmware.rescan.hba.retry.count=3*
+
Especifica la cantidad de tiempo, en milisegundos, durante el cual el plugin de SnapCenter para VMware vSphere espera entre cada envío de consultas sobre el reexamen del adaptador de bus de host debido a «...time limit for holding off I/O...» errores.

+
El valor predeterminado es "3".

* *vmware.rescan.hba.retry.delay=30000*
+
Especifica la cantidad máxima de veces que el plugin de SnapCenter para VMware vSphere reintenta reexaminar el adaptador del bus de host.

+
El valor predeterminado es "30000".


