---
permalink: scv_releasenotes_whats_new.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, scv, 6.2' 
summary: Obtenga información sobre las nuevas capacidades disponibles en el SnapCenter Plug-in for VMware vSphere 6.2. 
---
= Novedades del SnapCenter Plug-in for VMware vSphere 6.2
:allow-uri-read: 


[role="lead"]
Obtenga información sobre las nuevas capacidades disponibles en el SnapCenter Plug-in for VMware vSphere 6.2.

La versión 6.2 del SnapCenter Plug-in for VMware vSphere agrega compatibilidad con la copia de seguridad y la recuperación de máquinas virtuales (VM) en almacenes de datos VMFS para sistemas ASA r2 que ejecutan ONTAP 9.17.1 o posterior.  Con esta versión, puede realizar las siguientes operaciones para máquinas virtuales, almacenes de datos y formato de disco de máquina virtual (VMDK) en sistemas ASA r2:

* Grupos de consistencia de provisión para protección primaria
* Realizar copias de seguridad basadas en grupos de consistencia
* Utilice grupos de consistencia jerárquicos (disponibles con ONTAP 9.17.1 y versiones posteriores)
* Ejecutar flujos de trabajo de clonación
* Realizar flujos de trabajo de restauración
* Proporcionar protección secundaria al crear o modificar grupos de recursos (disponible con ONTAP 9.16.1 y versiones posteriores)

