---
permalink: scv_rn_upgrade_paths.html 
sidebar: sidebar 
keywords: upgrade paths, scv, 6.1 
summary: Descubra las nuevas funcionalidades disponibles en el complemento SnapCenter para VMware vSphere 6,1. 
---
= Vías de actualización para el SnapCenter Plug-in for VMware vSphere
:allow-uri-read: 


[role="lead"]
La versión del plugin de SnapCenter para VMware vSphere (SCV) a la que puede actualizar depende de la versión que esté ejecutando actualmente.

[NOTE]
====
La actualización a SnapCenter Plug-in for VMware vSphere (SCV) 4.8 y versiones posteriores solo es compatible con VMware vCenter Server 7 update 1 y versiones posteriores. Para VMware vCenter Server anterior a la versión 7 update 1, debes seguir usando SCV 4.7.

====
[cols="50%,50%"]
|===
| Si está en la versión SCV… | Puede actualizar directamente SCV a… 


 a| 
SCV 6,1
 a| 
SCV 6.2



 a| 
SCV 6,0
 a| 
SCV 6.1 y SCV 6.2



 a| 
SCV 5,0
 a| 
SCV 6,0 y SCV 6,1



 a| 
SCV 4,9
 a| 
SCV 5,0 y SCV 6,0

|===
Para bases de datos y sistemas de archivos virtualizados que están integrados con SnapCenter, esta es la ruta de actualización:

[cols="30%,30%,40%"]
|===
| Si está utilizando | Si su complemento de VMware es… | Puede actualizar directamente a… 


 a| 
SnapCenter 6.2
 a| 
SCV 6,1
 a| 
SCV 6.2



 a| 
SnapCenter 6,1
 a| 
SCV 6,0
 a| 
SCV 6,1



 a| 
SnapCenter 6,0
 a| 
SCV 5,0
 a| 
SCV 6,0



 a| 
SnapCenter 5,0
 a| 
SCV 4,9
 a| 
SCV 5,0



 a| 
SnapCenter 4,9
 a| 
SCV 4,8
 a| 
SCV 4,9



 a| 
SnapCenter 4,8
 a| 
SCV 4,7
 a| 
SCV 4,8

|===
Para obtener la información más reciente sobre las versiones compatibles, consulte https://imt.netapp.com/imt/imt.jsp?components=180121;&solution=1517&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"^] (IMT).
